Mark as PYTHON_VERSIONS_INCOMPATIBLE=24 because of AttributeError: 'module' object has no attribute 'SEEK_CUR' see http://ftp.netbsd.org/pub/pkgsrc/misc/joerg/20120308.0100/py24-filesystem-0.4.0/build.log